#!/bin/bash -l
#SBATCH --job-name=399e61e9-4d5e-11ed-9274-525400692cc9-m1
#SBATCH --partition=k2-gpu
#SBATCH --time=00:30:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem-per-cpu=4G
#SBATCH --gres=gpu:v100:1


conda activate catorch2


python -u /users/40247882/repository/EANN/eann --config ./config.yaml train 2>&1 > train.out
python -u /users/40247882/repository/EANN/eann --config ./config.yaml freeze EANN.pth -o eann_latest_ 2>&1 > freeze.out