ase_args:
  format: extxyz
dtype: torch.float32
extra_fixed_fields:
  r_max: 6.0
file_name: /users/40247882/repository/GDPy/examples/expedition/online/nequip/aqueous/surf22-fixed/init/t0/m0/dataset.xyz
force_fixed_keys: !!set {}
include_frames: null
include_keys: null
key_mapping: null
nequip_version: 0.5.5
root: /users/40247882/repository/GDPy/examples/expedition/online/nequip/aqueous/surf22-fixed/init/t0/m0
url: null
