collect:
  traj_period: 2
create:
  driver:
    backend: external
    init:
      Tdamp: 100
      dump_period: 4
      md_style: nvt
      temp:
      - 300
      - 600
      - 1500
      timestep: 2
    run:
      steps: 12
    task: md
select:
- method: invariant
  params: null
- fmax: 0.8
  method: convergence
- criteria:
    atomic_energy:
    - 0.01
    - 0.25
    force:
    - 0.05
    - 0.25
  method: deviation
  properties:
    atomic_energy: max_devi_e
    force: max_devi_f
  random_seed: 1112
- criteria:
    method: cur
    strategy: descent
    zeta: -1
  descriptor:
    average: inner
    lmax: 8
    name: soap
    nmax: 12
    periodic: true
    rcut: 6.0
    sigma: 0.3
    species:
    - C
    - H
    - O
    - Pt
  method: descriptor
  number:
  - 2
  - 0.2
  random_seed: 1112
systems:
- surf22-fixed
